const LUA_KEYWORDS = [
  // Keywords
  "and",
  "break",
  "do",
  "else",
  "elseif",
  "end",
  "false",
  "for",
  "function",
  "goto",
  "if",
  "in",
  "local",
  "nil",
  "not",
  "or",
  "repeat",
  "return",
  "then",
  "true",
  "until",
  "while",
].map((kw) => ({ label: kw, type: "keyword" }));

const LUA_BUILTINS = [
  // Standard library functions
  "assert",
  "collectgarbage",
  "dofile",
  "error",
  "getmetatable",
  "ipairs",
  "load",
  "loadfile",
  "next",
  "pairs",
  "pcall",
  "print",
  "rawequal",
  "rawget",
  "rawlen",
  "rawset",
  "require",
  "select",
  "setmetatable",
  "tonumber",
  "tostring",
  "type",
  "xpcall",
  // String library
  "string.byte",
  "string.char",
  "string.dump",
  "string.find",
  "string.format",
  "string.gmatch",
  "string.gsub",
  "string.len",
  "string.lower",
  "string.match",
  "string.rep",
  "string.reverse",
  "string.sub",
  "string.upper",
  // Table library
  "table.concat",
  "table.insert",
  "table.move",
  "table.remove",
  "table.sort",
  "table.unpack",
  // Math library
  "math.abs",
  "math.ceil",
  "math.floor",
  "math.sqrt",
  "math.max",
  "math.min",
  "math.random",
  "math.randomseed",
  "math.pi",
  "math.huge",
  "math.sin",
  "math.cos",
  "math.tan",
  "math.exp",
  "math.log",
  // IO / OS
  "io.read",
  "io.write",
  "io.open",
  "io.close",
  "io.lines",
  "os.time",
  "os.date",
  "os.clock",
  "os.exit",
  "os.getenv",
  // Coroutine
  "coroutine.create",
  "coroutine.resume",
  "coroutine.yield",
  "coroutine.status",
  "coroutine.wrap",
  "coroutine.running",
].map((fn) => ({ label: fn, type: "function" }));

export default [...LUA_KEYWORDS, ...LUA_BUILTINS];
