import { BlendFunction } from "postprocessing";
import type {
  StylePresetDefinition,
  StylePresetId,
} from "@/types/style-presets";

export const STYLE_PRESETS: Record<StylePresetId, StylePresetDefinition> = {
  "ps1-character": {
    id: "ps1-character",
    name: "PS1 Character",
    description:
      "A rough character-capture recipe with low-res textures, palette limits, hard shading, and chunky post effects.",
    materialPresetId: "ps1-character",
    materialValues: {
      color: "#d8b98f",
      roughness: 1,
      metalness: 0,
      lightingMode: "flat",
      flatShading: true,
      nearestFiltering: true,
      textureSize: 128,
      paletteColors: 32,
      dithering: true,
    },
    targets: {
      triangleBudget: 800,
      textureSize: 128,
      paletteColors: 32,
      flatShading: true,
      snapVertices: 0.025,
      animationFps: 10,
      nearestFiltering: true,
      dither: true,
      affineTexture: true,
      vertexLighting: "harsh",
    },
    renderDefaults: {
      width: 128,
      height: 128,
      exportWidth: 64,
      exportHeight: 64,
      cameraType: "perspective",
      cameraDistance: 4,
    },
    effects: [
      { type: "pixelation", props: { granularity: 3 } },
      { type: "colorDepth", props: { bits: 8 } },
      { type: "dither", props: { ditherStrength: 0.35, ditherScale: 1 } },
      { type: "gammaCorrection", props: { gamma: 2 } },
    ],
    pipelineNotes: [
      "Geometry decimation, vertex snapping, and affine-style UV warping are marked as targets for the upcoming model pipeline.",
      "Nearest filtering, palette limits, flat material shading, capture FPS, and post effects apply immediately.",
    ],
  },
  "low-poly-clean": {
    id: "low-poly-clean",
    name: "Low Poly Clean",
    description:
      "Clean flat surfaces, simplified colors, and production-friendly capture defaults.",
    materialPresetId: "low-poly-flat",
    materialValues: {
      color: "#cfc7b8",
      roughness: 0.9,
      metalness: 0,
      lightingMode: "flat",
      flatShading: true,
      nearestFiltering: false,
      textureSize: 256,
      paletteColors: 48,
      dithering: false,
    },
    targets: {
      triangleBudget: 1500,
      textureSize: 256,
      paletteColors: 48,
      flatShading: true,
      animationFps: 12,
      nearestFiltering: false,
      dither: false,
      bakedAo: true,
      vertexLighting: "soft",
    },
    renderDefaults: {
      width: 256,
      height: 256,
      exportWidth: 96,
      exportHeight: 96,
      cameraType: "orthographic",
      cameraDistance: 5,
    },
    effects: [
      { type: "brightnessContrast", props: { brightness: 0, contrast: 0.08 } },
      { type: "gammaCorrection", props: { gamma: 2 } },
    ],
    pipelineNotes: [
      "Triangle reduction and optional baked AO are style targets until the model-processing pass lands.",
      "Flat material shading, cleaner colors, orthographic camera, and capture FPS apply immediately.",
    ],
  },
  "pixel-art-3d": {
    id: "pixel-art-3d",
    name: "Pixel Art 3D",
    description:
      "Small orthographic sprites with hard edges, low-res texture targets, and stepped animation timing.",
    materialPresetId: "unlit-sprite",
    materialValues: {
      color: "#ffffff",
      roughness: 1,
      metalness: 0,
      lightingMode: "unlit",
      flatShading: true,
      nearestFiltering: true,
      textureSize: 64,
      paletteColors: 16,
      dithering: false,
    },
    targets: {
      textureSize: 64,
      paletteColors: 16,
      flatShading: true,
      animationFps: 8,
      nearestFiltering: true,
      dither: false,
      orthographic: true,
      vertexLighting: "none",
    },
    renderDefaults: {
      width: 128,
      height: 128,
      exportWidth: 48,
      exportHeight: 48,
      cameraType: "orthographic",
      cameraDistance: 5,
    },
    effects: [
      { type: "pixelation", props: { granularity: 4 } },
      { type: "colorDepth", props: { bits: 8 } },
      { type: "gammaCorrection", props: { gamma: 2 } },
    ],
    pipelineNotes: [
      "Texture-atlas generation is represented by texture size and palette targets for now.",
      "Orthographic camera, hard material settings, stepped capture FPS, and pixel effects apply immediately.",
    ],
  },
  "retro-horror": {
    id: "retro-horror",
    name: "Retro Horror",
    description:
      "Dark PS1-style capture with limited palette, heavy dither, vignette, and lower camera distance.",
    materialPresetId: "retro-horror",
    materialValues: {
      color: "#7f7268",
      roughness: 1,
      metalness: 0,
      emissive: "#080505",
      emissiveIntensity: 0.08,
      lightingMode: "flat",
      flatShading: true,
      nearestFiltering: true,
      textureSize: 128,
      paletteColors: 24,
      dithering: true,
    },
    targets: {
      triangleBudget: 700,
      textureSize: 128,
      paletteColors: 24,
      flatShading: true,
      snapVertices: 0.035,
      animationFps: 10,
      nearestFiltering: true,
      dither: true,
      affineTexture: true,
      vertexLighting: "harsh",
      lowDrawDistance: 18,
    },
    renderDefaults: {
      width: 128,
      height: 128,
      exportWidth: 64,
      exportHeight: 64,
      cameraType: "perspective",
      cameraDistance: 3.5,
    },
    effects: [
      { type: "pixelation", props: { granularity: 3 } },
      { type: "colorDepth", props: { bits: 7 } },
      { type: "dither", props: { ditherStrength: 0.48, ditherScale: 1 } },
      {
        type: "brightnessContrast",
        props: {
          brightness: -0.08,
          contrast: 0.18,
          blendFunction: BlendFunction.SRC,
        },
      },
      { type: "vignette", props: { offset: 0.42, darkness: 0.72 } },
      { type: "noise", props: { premultiply: false } },
      { type: "gammaCorrection", props: { gamma: 2 } },
    ],
    pipelineNotes: [
      "Fog and low draw distance are style targets until scene-level fog controls are added.",
      "Dark material settings, dither, vignette, palette depth, and capture FPS apply immediately.",
    ],
  },
};

export const STYLE_PRESET_LIST = Object.values(STYLE_PRESETS);
