import type { SpritesheetJSON } from "../assets";

export const createRaylibH = (
  json: SpritesheetJSON,
  imagePath = "spritesheet.png",
): string => {
  const toFloat = (n: number) => (Number.isInteger(n) ? `${n}.0f` : `${n}f`);

  const toIdentifier = (name: string) =>
    name.replace(/[^a-zA-Z0-9_]/g, "_").replace(/^([0-9])/, "_$1");

  const toPascal = (name: string) =>
    toIdentifier(name)
      .split("_")
      .map((w) => w.charAt(0).toUpperCase() + w.slice(1))
      .join("");

  const guardName = "SPRITESHEET_H";
  const lines: string[] = [];

  lines.push(`// Generated by Sprite Sheet Helper`);
  lines.push(`// ${json.meta.exportedAt}`);
  lines.push(`//`);
  lines.push(`// Requires raylib — https://www.raylib.com`);
  lines.push(`// Place "${imagePath}" next to your executable, then:`);
  lines.push(`//`);
  lines.push(`//   Texture2D sheet = LoadTexture(SPRITESHEET_PATH);`);
  lines.push(
    `//   Animation walk   = Create${toPascal(json.animations[0]?.name ?? "Walk")}Animation();`,
  );
  lines.push(`//   UpdateAnimation(&walk, GetFrameTime());`);
  lines.push(`//   DrawAnimation(&walk, sheet, x, y, WHITE);`);
  lines.push(``);
  lines.push(`#ifndef ${guardName}`);
  lines.push(`#define ${guardName}`);
  lines.push(``);
  lines.push(`#include "raylib.h"`);
  lines.push(``);
  lines.push(`#define SPRITESHEET_PATH "${imagePath}"`);
  lines.push(``);
  lines.push(`typedef struct {`);
  lines.push(`    Rectangle *frames;`);
  lines.push(`    int        frame_count;`);
  lines.push(`    float      fps;`);
  lines.push(`    int        frame_width;`);
  lines.push(`    int        frame_height;`);
  lines.push(`    int        current_frame;`);
  lines.push(`    float      timer;`);
  lines.push(`} Animation;`);
  lines.push(``);
  lines.push(`static inline void UpdateAnimation(Animation *anim, float dt) {`);
  lines.push(`    anim->timer += dt;`);
  lines.push(`    if (anim->timer >= 1.0f / anim->fps) {`);
  lines.push(`        anim->timer -= 1.0f / anim->fps;`);
  lines.push(
    `        anim->current_frame = (anim->current_frame + 1) % anim->frame_count;`,
  );
  lines.push(`    }`);
  lines.push(`}`);
  lines.push(``);
  lines.push(`static inline void DrawAnimation(`);
  lines.push(`    Animation *anim, Texture2D sheet, int x, int y, Color tint`);
  lines.push(`) {`);
  lines.push(`    DrawTextureRec(`);
  lines.push(`        sheet,`);
  lines.push(`        anim->frames[anim->current_frame],`);
  lines.push(`        (Vector2){ (float)x, (float)y },`);
  lines.push(`        tint`);
  lines.push(`    );`);
  lines.push(`}`);
  lines.push(``);

  for (const anim of json.animations) {
    const varName = toIdentifier(anim.name).toLowerCase();
    const pascal = toPascal(anim.name);

    lines.push(`// ${anim.name}`);
    lines.push(`static Rectangle ${varName}_frames[] = {`);
    for (const quad of anim.quads) {
      lines.push(
        `    { ${toFloat(quad.x)}, ${toFloat(quad.y)}, ${toFloat(quad.w)}, ${toFloat(quad.h)} },`,
      );
    }
    lines.push(`};`);
    lines.push(``);
    lines.push(`static inline Animation Create${pascal}Animation(void) {`);
    lines.push(`    Animation anim = {`);
    lines.push(`        .frames        = ${varName}_frames,`);
    lines.push(`        .frame_count   = ${anim.quads.length},`);
    lines.push(`        .fps           = ${toFloat(anim.fps)},`);
    lines.push(`        .frame_width   = ${anim.frameWidth},`);
    lines.push(`        .frame_height  = ${anim.frameHeight},`);
    lines.push(`        .current_frame = 0,`);
    lines.push(`        .timer         = 0.0f,`);
    lines.push(`    };`);
    lines.push(`    return anim;`);
    lines.push(`}`);
    lines.push(``);
  }

  lines.push(`#endif // ${guardName}`);

  return lines.join("\n");
};

export const createRaylibExample = (json: SpritesheetJSON): string => {
  const firstName = json.animations[0]?.name ?? "walk";
  const pascal = firstName
    .replace(/[^a-zA-Z0-9_]/g, "_")
    .split("_")
    .map((w) => w.charAt(0).toUpperCase() + w.slice(1))
    .join("");

  return [
    `#include "raylib.h"`,
    `#include "spritesheet.h"`,
    ``,
    `int main(void) {`,
    `    InitWindow(320, 240, "Sprite Animation");`,
    `    SetTargetFPS(60);`,
    ``,
    `    Texture2D sheet = LoadTexture(SPRITESHEET_PATH);`,
    `    Animation  anim  = Create${pascal}Animation();`,
    ``,
    `    while (!WindowShouldClose()) {`,
    `        UpdateAnimation(&anim, GetFrameTime());`,
    ``,
    `        BeginDrawing();`,
    `            ClearBackground(BLACK);`,
    `            DrawAnimation(&anim, sheet, 144, 104, WHITE);`,
    `        EndDrawing();`,
    `    }`,
    ``,
    `    UnloadTexture(sheet);`,
    `    CloseWindow();`,
    `    return 0;`,
    `}`,
  ].join("\n");
};
