import type { SpritesheetJSON } from "../assets";

export const createGodotGD = (
  json: SpritesheetJSON,
  imagePath = "spritesheet.png",
): string => {
  const T = "\t"; // GDScript indents with tabs
  const lines: string[] = [];

  lines.push(`# Generated by Sprite Sheet Helper`);
  lines.push(`# ${json.meta.exportedAt}`);
  lines.push(`#`);
  lines.push(`# Place "${imagePath}" in your project (e.g. res://assets/) and`);
  lines.push(`# update SHEET_PATH below.`);
  lines.push(`#`);
  lines.push(`# Usage:`);
  lines.push(`#   var animated_sprite := AnimatedSprite2D.new()`);
  lines.push(
    `#   animated_sprite.sprite_frames = SpriteSheetHelper.create_sprite_frames()`,
  );
  lines.push(
    `#   animated_sprite.play("${json.animations[0]?.name ?? "walk"}")`,
  );
  lines.push(`#   add_child(animated_sprite)`);
  lines.push(``);
  lines.push(`class_name SpriteSheetHelper`);
  lines.push(`extends RefCounted`);
  lines.push(``);
  lines.push(`const SHEET_PATH = "res://${imagePath}"`);
  lines.push(``);
  lines.push(`static func create_sprite_frames() -> SpriteFrames:`);
  lines.push(`${T}var texture: Texture2D = load(SHEET_PATH)`);
  lines.push(`${T}var frames := SpriteFrames.new()`);
  lines.push(`${T}frames.remove_animation(&"default")`);
  lines.push(``);

  for (const anim of json.animations) {
    lines.push(`${T}# ${anim.name}`);
    lines.push(`${T}frames.add_animation(&"${anim.name}")`);
    lines.push(`${T}frames.set_animation_speed(&"${anim.name}", ${anim.fps})`);
    lines.push(`${T}frames.set_animation_loop(&"${anim.name}", true)`);
    lines.push(`${T}for region: Rect2 in [`);
    for (const quad of anim.quads) {
      lines.push(`${T}${T}Rect2(${quad.x}, ${quad.y}, ${quad.w}, ${quad.h}),`);
    }
    lines.push(`${T}]:`);
    lines.push(`${T}${T}var atlas := AtlasTexture.new()`);
    lines.push(`${T}${T}atlas.atlas = texture`);
    lines.push(`${T}${T}atlas.region = region`);
    lines.push(`${T}${T}frames.add_frame(&"${anim.name}", atlas)`);
    lines.push(``);
  }

  lines.push(`${T}return frames`);

  return lines.join("\n");
};

export const createGodotExample = (json: SpritesheetJSON): string => {
  const firstName = json.animations[0]?.name ?? "walk";
  return [
    `extends Node2D`,
    ``,
    `var animated_sprite: AnimatedSprite2D`,
    ``,
    `func _ready() -> void:`,
    `\tanimated_sprite = AnimatedSprite2D.new()`,
    `\tanimated_sprite.sprite_frames = SpriteSheetHelper.create_sprite_frames()`,
    `\tanimated_sprite.position = Vector2(160, 120)`,
    `\tadd_child(animated_sprite)`,
    `\tanimated_sprite.play("${firstName}")`,
    ``,
    `func _process(_delta: float) -> void:`,
    `\t# your game logic here`,
    `\tpass`,
  ].join("\n");
};
