import type { Exporter } from "@/types/file";
import type { SpritesheetJSON } from "../assets";
import { buildSpritesheetAssets } from "./helpers";

export const createVanillaLua = (
  json: SpritesheetJSON,
  imagePath = "spritesheet.png",
): string => {
  const lines: string[] = [];

  lines.push(`-- Generated by Sprite Sheet Helper`);
  lines.push(`-- ${json.meta.exportedAt}`);
  lines.push(``);
  lines.push(`local M = {}`);
  lines.push(``);
  lines.push(`function M.load(imagePath)`);
  lines.push(`\timagePath = imagePath or "${imagePath}"`);
  lines.push(`\tlocal image = love.graphics.newImage(imagePath)`);
  lines.push(`\tlocal iw, ih = image:getDimensions()`);
  lines.push(``);
  lines.push(`\tlocal animations = {}`);
  lines.push(``);

  for (const anim of json.animations) {
    lines.push(`\t-- ${anim.name}`);
    lines.push(`\tdo`);
    lines.push(`\t\tlocal frames = {}`);

    for (const quad of anim.quads) {
      lines.push(
        `\t\ttable.insert(frames, love.graphics.newQuad(${quad.x}, ${quad.y}, ${quad.w}, ${quad.h}, iw, ih))`,
      );
    }

    lines.push(``);
    lines.push(`\t\tanimations["${anim.name}"] = {`);
    lines.push(`\t\t\tframes = frames,`);
    lines.push(`\t\t\tfps = ${anim.fps},`);
    lines.push(`\t\t\tframeWidth = ${anim.frameWidth},`);
    lines.push(`\t\t\tframeHeight = ${anim.frameHeight},`);
    lines.push(`\t\t\tcurrentFrame = 1,`);
    lines.push(`\t\t\ttimer = 0,`);
    lines.push(`\t\t}`);
    lines.push(`\tend`);
    lines.push(``);
  }

  lines.push(`\treturn {`);
  lines.push(`\t\timage = image,`);
  lines.push(`\t\tanimations = animations,`);
  lines.push(`\t}`);
  lines.push(`end`);
  lines.push(``);

  lines.push(`function M:update(currentAnimation, dt)`);
  lines.push(`\tlocal anim = self.animations[currentAnimation]`);
  lines.push(`\tanim.timer = anim.timer + dt`);
  lines.push(`\tif anim.timer >= 1 / anim.fps then`);
  lines.push(`\t\tanim.timer = anim.timer - 1 / anim.fps`);
  lines.push(`\t\tanim.currentFrame = (anim.currentFrame % #anim.frames) + 1`);
  lines.push(`\tend`);
  lines.push(`end`);
  lines.push(``);
  lines.push(`function M:draw(currentAnimation, x, y)`);
  lines.push(`\tlocal anim = self.animations[currentAnimation]`);
  lines.push(
    `\tlove.graphics.draw(self.image, anim.frames[anim.currentFrame], x, y)`,
  );
  lines.push(`end`);
  lines.push(``);
  lines.push(`return M`);

  return lines.join("\n");
};

export const createAnim8Lua = (
  json: SpritesheetJSON,
  imagePath = "spritesheet.png",
): string => {
  const lines: string[] = [];

  lines.push(`-- Generated by Sprite Sheet Helper`);
  lines.push(`-- ${json.meta.exportedAt}`);
  lines.push(`-- Requires anim8: https://github.com/kikito/anim8`);
  lines.push(``);
  lines.push(`local anim8 = require("anim8")`);
  lines.push(`local M = {}`);
  lines.push(``);
  lines.push(`function M.load(imagePath)`);
  lines.push(`\timagePath = imagePath or "${imagePath}"`);
  lines.push(`\tlocal image = love.graphics.newImage(imagePath)`);
  lines.push(`\tlocal iw, ih = image:getDimensions()`);
  lines.push(``);
  lines.push(`\tlocal animations = {}`);
  lines.push(``);

  for (const anim of json.animations) {
    const frameCount = anim.quads.length;
    const frameDuration = Number((1 / anim.fps).toFixed(4));

    const originX = anim.quads[0].x;
    const originY = anim.quads[0].y;

    lines.push(`\t-- ${anim.name}`);
    lines.push(`\tdo`);
    lines.push(
      `\t\tlocal g = anim8.newGrid(${anim.frameWidth}, ${anim.frameHeight}, iw, ih, ${originX}, ${originY})`,
    );
    lines.push(
      `\t\tanimations["${anim.name}"] = anim8.newAnimation(g("1-${frameCount}", 1), ${frameDuration})`,
    );
    lines.push(`\tend`);
    lines.push(``);
  }

  lines.push(`\treturn {`);
  lines.push(`\t\timage = image,`);
  lines.push(`\t\tanimations = animations,`);
  lines.push(`\t}`);
  lines.push(`end`);
  lines.push(``);

  lines.push(`function M:update(currentAnimation, dt)`);
  lines.push(`\tself.animations[currentAnimation]:update(dt)`);
  lines.push(`end`);
  lines.push(``);
  lines.push(`function M:draw(currentAnimation, x, y)`);
  lines.push(`\tself.animations[currentAnimation]:draw(self.image, x, y)`);
  lines.push(`end`);
  lines.push(``);
  lines.push(`return M`);

  return lines.join("\n");
};

export const createLuaExample = (json: SpritesheetJSON): string => {
  const firstName = json.animations[0]?.name ?? "walk";
  return [
    `local spritesheet = require("spritesheet")`,
    ``,
    `local sheet`,
    ``,
    `function love.load()`,
    `\tsheet = spritesheet.load()`,
    `end`,
    ``,
    `function love.update(dt)`,
    `\tspritesheet.update(sheet, "${firstName}", dt)`,
    `end`,
    ``,
    `function love.draw()`,
    `\tspritesheet.draw(sheet, "${firstName}", 100, 100)`,
    `end`,
  ].join("\n");
};

export const love2dVanillaExporter: Exporter<"love2d-lua"> = {
  id: "love2d-lua",
  label: "Love2D (Lua)",

  async run({ exportedImages }) {
    const { json, base64PNG } = await buildSpritesheetAssets(exportedImages);

    return {
      filename: "lua.zip",
      files: [
        { name: "spritesheet.png", content: base64PNG, base64: true },
        { name: "spritesheet.json", content: JSON.stringify(json, null, 2) },
        { name: "spritesheet.lua", content: createVanillaLua(json) },
        { name: "main.lua", content: createLuaExample(json) },
      ],
    };
  },
};

export const love2dAnim8Exporter: Exporter<"love2d-anim8"> = {
  id: "love2d-anim8",
  label: "Love2D (Anim8)",

  async run({ exportedImages }) {
    const { json, base64PNG } = await buildSpritesheetAssets(exportedImages);

    return {
      filename: "anim8.zip",
      files: [
        { name: "spritesheet.png", content: base64PNG, base64: true },
        { name: "spritesheet.json", content: JSON.stringify(json, null, 2) },
        { name: "spritesheet.lua", content: createAnim8Lua(json) },
        { name: "main.lua", content: createLuaExample(json) },
      ],
    };
  },
};
