import type { SpritesheetJSON } from "../assets";

export const createVanillaLua = (
  json: SpritesheetJSON,
  imagePath = "spritesheet.png",
): string => {
  const lines: string[] = [];

  lines.push(`-- Generated by Sprite Sheet Helper`);
  lines.push(`-- ${json.meta.exportedAt}`);
  lines.push(``);
  lines.push(`local M = {}`);
  lines.push(``);
  lines.push(`function M.load(imagePath)`);
  lines.push(`  imagePath = imagePath or "${imagePath}"`);
  lines.push(`  local image = love.graphics.newImage(imagePath)`);
  lines.push(`  local iw, ih = image:getDimensions()`);
  lines.push(``);
  lines.push(`  local animations = {}`);
  lines.push(``);

  for (const anim of json.animations) {
    lines.push(`  -- ${anim.name}`);
    lines.push(`  do`);
    lines.push(`    local frames = {}`);

    for (const quad of anim.quads) {
      lines.push(
        `    table.insert(frames, love.graphics.newQuad(${quad.x}, ${quad.y}, ${quad.w}, ${quad.h}, iw, ih))`,
      );
    }

    lines.push(``);
    lines.push(`    animations["${anim.name}"] = {`);
    lines.push(`      frames = frames,`);
    lines.push(`      fps = ${anim.fps},`);
    lines.push(`      frameWidth = ${anim.frameWidth},`);
    lines.push(`      frameHeight = ${anim.frameHeight},`);
    lines.push(`      currentFrame = 1,`);
    lines.push(`      timer = 0,`);
    lines.push(`    }`);
    lines.push(`  end`);
    lines.push(``);
  }

  lines.push(`  return {`);
  lines.push(`    image = image,`);
  lines.push(`    animations = animations,`);
  lines.push(`  }`);
  lines.push(`end`);
  lines.push(``);

  // Minimal update/draw helpers so it works out of the box
  lines.push(`function M.update(anim, dt)`);
  lines.push(`  anim.timer = anim.timer + dt`);
  lines.push(`  if anim.timer >= 1 / anim.fps then`);
  lines.push(`    anim.timer = anim.timer - 1 / anim.fps`);
  lines.push(`    anim.currentFrame = (anim.currentFrame % #anim.frames) + 1`);
  lines.push(`  end`);
  lines.push(`end`);
  lines.push(``);
  lines.push(`function M.draw(anim, image, x, y)`);
  lines.push(
    `  love.graphics.draw(image, anim.frames[anim.currentFrame], x, y)`,
  );
  lines.push(`end`);
  lines.push(``);
  lines.push(`return M`);

  return lines.join("\n");
};

export const createAnim8Lua = (
  json: SpritesheetJSON,
  imagePath = "spritesheet.png",
): string => {
  const lines: string[] = [];

  lines.push(`-- Generated by Sprite Sheet Helper`);
  lines.push(`-- ${json.meta.exportedAt}`);
  lines.push(`-- Requires anim8: https://github.com/kikito/anim8`);
  lines.push(``);
  lines.push(`local anim8 = require 'anim8'`);
  lines.push(`local M = {}`);
  lines.push(``);
  lines.push(`function M.load(imagePath)`);
  lines.push(`  imagePath = imagePath or "${imagePath}"`);
  lines.push(`  local image = love.graphics.newImage(imagePath)`);
  lines.push(`  local iw, ih = image:getDimensions()`);
  lines.push(``);
  lines.push(`  local animations = {}`);
  lines.push(``);

  for (const anim of json.animations) {
    const frameCount = anim.quads.length;
    const frameDuration = Number((1 / anim.fps).toFixed(4));

    // anim8 grid is uniform per row — origin is the first quad's x/y
    const originX = anim.quads[0].x;
    const originY = anim.quads[0].y;

    lines.push(`  -- ${anim.name}`);
    lines.push(`  do`);
    lines.push(
      `    local g = anim8.newGrid(${anim.frameWidth}, ${anim.frameHeight}, iw, ih, ${originX}, ${originY})`,
    );
    lines.push(
      `    animations["${anim.name}"] = anim8.newAnimation(g('1-${frameCount}', 1), ${frameDuration})`,
    );
    lines.push(`  end`);
    lines.push(``);
  }

  lines.push(`  return {`);
  lines.push(`    image = image,`);
  lines.push(`    animations = animations,`);
  lines.push(`  }`);
  lines.push(`end`);
  lines.push(``);

  // Standard anim8 update/draw
  lines.push(`function M.update(sprite, dt)`);
  lines.push(`  sprite.animations[sprite.currentAnimation]:update(dt)`);
  lines.push(`end`);
  lines.push(``);
  lines.push(`function M.draw(sprite, x, y)`);
  lines.push(
    `  sprite.animations[sprite.currentAnimation]:draw(sprite.image, x, y)`,
  );
  lines.push(`end`);
  lines.push(``);
  lines.push(`return M`);

  return lines.join("\n");
};
