import type { Exporter } from "@/types/file";
import type { SpritesheetJSON } from "../assets";
import { buildSpritesheetAssets } from "./helpers";

export const createPhaserAtlasJSON = (
  json: SpritesheetJSON,
  imagePath = "spritesheet.png",
): string => {
  const frames: Record<string, object> = {};

  for (const anim of json.animations) {
    anim.quads.forEach((quad, i) => {
      frames[`${anim.name}_${i}`] = {
        frame: { x: quad.x, y: quad.y, w: quad.w, h: quad.h },
        rotated: false,
        trimmed: false,
        spriteSourceSize: { x: 0, y: 0, w: quad.w, h: quad.h },
        sourceSize: { w: quad.w, h: quad.h },
      };
    });
  }

  return JSON.stringify(
    {
      frames,
      meta: {
        image: imagePath,
        scale: "1",
      },
    },
    null,
    2,
  );
};

export const createPhaserTS = (
  json: SpritesheetJSON,
  imagePath = "spritesheet.png",
): string => {
  const key = imagePath.replace(/\.[^/.]+$/, "");
  const lines: string[] = [];

  lines.push(`// Generated by Sprite Sheet Helper`);
  lines.push(`// ${json.meta.exportedAt}`);
  lines.push(`//`);
  lines.push(
    `// 1. Add "spritesheet.png" and "spritesheet_atlas.json" to your assets folder.`,
  );
  lines.push(`// 2. Call preload() inside your Scene preload().`);
  lines.push(`// 3. Call createAnims() inside your Scene create().`);
  lines.push(``);
  lines.push(`const SHEET_KEY = "${key}";`);
  lines.push(``);
  lines.push(`export function preload(scene: Phaser.Scene): void {`);
  lines.push(
    `  scene.load.atlas(SHEET_KEY, "${imagePath}", "spritesheet_atlas.json");`,
  );
  lines.push(`}`);
  lines.push(``);
  lines.push(`export function createAnims(scene: Phaser.Scene): void {`);

  for (const anim of json.animations) {
    lines.push(``);
    lines.push(`  // ${anim.name}`);
    lines.push(`  scene.anims.create({`);
    lines.push(`    key: "${anim.name}",`);
    lines.push(`    frames: [`);
    anim.quads.forEach((_, i) => {
      lines.push(`      { key: SHEET_KEY, frame: "${anim.name}_${i}" },`);
    });
    lines.push(`    ],`);
    lines.push(`    frameRate: ${anim.fps},`);
    lines.push(`    repeat: -1,`);
    lines.push(`  });`);
  }

  lines.push(`}`);
  lines.push(``);
  lines.push(`// Usage:`);
  lines.push(`//   const sprite = scene.add.sprite(x, y, SHEET_KEY);`);
  lines.push(`//   sprite.play("${json.animations[0]?.name ?? "animName"}");`);

  return lines.join("\n");
};

export const createPhaserExample = (json: SpritesheetJSON): string => {
  const firstName = json.animations[0]?.name ?? "walk";
  return [
    `import { Scene, GameObjects } from "phaser";`,
    ``,
    `import { preload, createAnims } from "./spritesheet_phaser";`,
    ``,
    `export class Game extends Scene {`,
    `  private player!: GameObjects.Sprite;`,
    `  constructor() {`,
    `    super("Game");`,
    `  }`,
    ``,
    `  preload() {`,
    `    this.load.setPath("assets");`,
    `    preload(this);`,
    `  }`,
    ``,
    `  create() {`,
    `    createAnims(this);`,
    `    this.player = this.add.sprite(160, 120, "spritesheet");`,
    `    this.player.play("${firstName}");`,
    `  }`,
    `}`,
  ].join("\n");
};

export const phaserExporter: Exporter<"phaser"> = {
  id: "phaser",
  label: "PhaserJS",

  async run({ exportedImages }) {
    const { json, base64PNG } = await buildSpritesheetAssets(exportedImages);

    return {
      filename: "phaser.zip",
      files: [
        { name: "spritesheet.png", content: base64PNG, base64: true },
        {
          name: "spritesheet_atlas.json",
          content: createPhaserAtlasJSON(json),
        },
        { name: "spritesheet_phaser.ts", content: createPhaserTS(json) },
        { name: "example.ts", content: createPhaserExample(json) },
      ],
    };
  },
};
