import type { Exporter } from "@/types/file";
import type { SpritesheetJSON } from "../assets";
import { buildSpritesheetAssets } from "./helpers";

export const createTurboRust = (
  json: SpritesheetJSON,
  imagePath = "spritesheet.png",
): string => {
  // Derive the sprite! name from the filename (no extension)
  const spriteName = imagePath.replace(/\.[^/.]+$/, "");

  const lines: string[] = [];

  lines.push(`// Generated by Sprite Sheet Helper`);
  lines.push(`// ${json.meta.exportedAt}`);
  lines.push(`//`);
  lines.push(
    `// SETUP: Place "${imagePath}" in your project's sprites/ folder.`,
  );
  lines.push(``);

  // ── Structs ──────────────────────────────────────────────────────────────
  lines.push(`#[derive(Clone)]`);
  lines.push(`pub struct AnimationFrame {`);
  lines.push(`    pub x: i32,`);
  lines.push(`    pub y: i32,`);
  lines.push(`    pub w: u32,`);
  lines.push(`    pub h: u32,`);
  lines.push(`}`);
  lines.push(``);
  lines.push(`pub struct Animation {`);
  lines.push(`    pub frames: Vec<AnimationFrame>,`);
  lines.push(`    pub fps: f32,`);
  lines.push(`    pub frame_width: u32,`);
  lines.push(`    pub frame_height: u32,`);
  lines.push(`    pub current_frame: usize,`);
  lines.push(
    `    /// Tick counter — incremented each game loop (Turbo runs at 60 fps)`,
  );
  lines.push(`    pub tick: u32,`);
  lines.push(`}`);
  lines.push(``);

  // ── update ────────────────────────────────────────────────────────────────
  // Turbo has no dt — the loop runs at a fixed 60 fps, so we derive
  // ticks_per_frame from the animation's fps value.
  lines.push(`/// Call once per game tick inside your turbo::go! loop.`);
  lines.push(`pub fn update(anim: &mut Animation) {`);
  lines.push(`    anim.tick += 1;`);
  lines.push(`    let ticks_per_frame = (60.0 / anim.fps).round() as u32;`);
  lines.push(`    if anim.tick >= ticks_per_frame {`);
  lines.push(`        anim.tick = 0;`);
  lines.push(
    `        anim.current_frame = (anim.current_frame + 1) % anim.frames.len();`,
  );
  lines.push(`    }`);
  lines.push(`}`);
  lines.push(``);

  // ── draw ──────────────────────────────────────────────────────────────────
  // tx/ty offset into the spritesheet; w/h clip to the frame size.
  lines.push(`/// Call inside your turbo::go! loop to draw the current frame.`);
  lines.push(`pub fn draw(anim: &Animation, x: i32, y: i32) {`);
  lines.push(`    let frame = &anim.frames[anim.current_frame];`);
  lines.push(`    sprite!("${spriteName}",`);
  lines.push(`        x = x,`);
  lines.push(`        y = y,`);
  lines.push(`        w = anim.frame_width,`);
  lines.push(`        h = anim.frame_height,`);
  lines.push(`        tx = frame.x,`);
  lines.push(`        ty = frame.y`);
  lines.push(`    );`);
  lines.push(`}`);
  lines.push(``);

  // ── Per-animation constructor functions ───────────────────────────────────
  for (const anim of json.animations) {
    // Sanitise the animation name into a valid Rust identifier
    const fnName = anim.name
      .replace(/[^a-zA-Z0-9_]/g, "_")
      .replace(/^([0-9])/, "_$1")
      .toLowerCase();

    lines.push(`// "${anim.name}"`);
    lines.push(`pub fn ${fnName}() -> Animation {`);
    lines.push(`    Animation {`);
    lines.push(`        frames: vec![`);

    for (const quad of anim.quads) {
      lines.push(
        `            AnimationFrame { x: ${quad.x}, y: ${quad.y}, w: ${quad.w}, h: ${quad.h} },`,
      );
    }

    lines.push(`        ],`);
    lines.push(`        fps: ${anim.fps}_f32,`);
    lines.push(`        frame_width: ${anim.frameWidth},`);
    lines.push(`        frame_height: ${anim.frameHeight},`);
    lines.push(`        current_frame: 0,`);
    lines.push(`        tick: 0,`);
    lines.push(`    }`);
    lines.push(`}`);
    lines.push(``);
  }

  return lines.join("\n");
};

export const createTurboExample = (json: SpritesheetJSON): string => {
  const firstName = json.animations[0]?.name ?? "walk";
  const fnName = firstName
    .replace(/[^a-zA-Z0-9_]/g, "_")
    .replace(/^([0-9])/, "_$1")
    .toLowerCase();

  return [
    `use crate::spritesheet_turbo::*;`,
    ``,
    `turbo::go! {`,
    `    let mut player = ${fnName}();`,
    ``,
    `    loop {`,
    `        update(&mut player);`,
    `        draw(&player, 64, 64);`,
    `        tick!();`,
    `    }`,
    `}`,
  ].join("\n");
};

export const turboRustExporter: Exporter<"turbo"> = {
  id: "turbo",
  label: "Turbo (Rust)",

  async run({ exportedImages }) {
    const { json, base64PNG } = await buildSpritesheetAssets(exportedImages);

    return {
      filename: "turbo.zip",
      files: [
        { name: "spritesheet.png", content: base64PNG, base64: true },
        { name: "spritesheet.json", content: JSON.stringify(json, null, 2) },
        { name: "spritesheet_turbo.rs", content: createTurboRust(json) },
        { name: "example.rs", content: createTurboExample(json) },
      ],
    };
  },
};
